version: '3'
services:
  demo-app:
    # Files containing environment variables that will be included
    env_file: .env
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
  app-db:
    # Files containing environment variables that will be included
    env_file: .env
    image: mysql:8.0
    platform: linux/x86_64  # M1 Macの場合必要
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 13306:3306  # ホストマシンのポート13306を、docker内のポート3306に接続する
volumes:
  mysql_data: