version: '3'
services:
  demo-app:
    # Files containing environment variables that will be included
    env_file: .env
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
  app-db:
    # Files containing environment variables that will be included
    env_file: .env
    image: postgres:14.1-alpine
    platform: linux/x86_64  # M1 Macの場合必要
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 15432:5432  # ホストマシンのポート13306を、docker内のポート3306に接続する

volumes:
    postgres_data: