"""1_create_custom_schema_and_db

Revision ID: 5f9053daa6ea
Revises: 
Create Date: 2022-01-18 21:36:49.358966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f9053daa6ea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ============================================================
    # [MANUAL]CREATE SCHEMA IF NOT EXISTS "todoist";
    # ============================================================
    op.execute('CREATE SCHEMA IF NOT EXISTS "todoist";')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("detail", sa.String(length=4096), nullable=False),
        sa.Column("status_type", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="todoist",
    )
    op.create_index(
        op.f("ix_todoist_tasks_status_type"),
        "tasks",
        ["status_type"],
        unique=False,
        schema="todoist",
    )
    op.create_index(
        op.f("ix_todoist_tasks_title"), "tasks", ["title"], unique=False, schema="todoist"
    )
    op.create_table(
        "dones",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("note", sa.String(length=4096), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["todoist.tasks.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="todoist",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dones", schema="todoist")
    op.drop_index(op.f("ix_todoist_tasks_title"), table_name="tasks", schema="todoist")
    op.drop_index(op.f("ix_todoist_tasks_status_type"), table_name="tasks", schema="todoist")
    op.drop_table("tasks", schema="todoist")
    # ### end Alembic commands ###

    # ============================================================
    # [MANUAL]DROP SCHEMA IF EXISTS "todoist";
    # ============================================================
    op.execute('DROP SCHEMA IF EXISTS "todoist";')
