"""2_create_tasks_and_dones_table

Revision ID: 882759e705fc
Revises: 81052877c664
Create Date: 2022-01-18 22:01:00.169275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "882759e705fc"
down_revision = "81052877c664"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("detail", sa.String(length=4096), nullable=False),
        sa.Column("status_type", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="todoist",
    )
    op.create_index(
        op.f("ix_todoist_tasks_status_type"),
        "tasks",
        ["status_type"],
        unique=False,
        schema="todoist",
    )
    op.create_index(
        op.f("ix_todoist_tasks_title"), "tasks", ["title"], unique=False, schema="todoist"
    )
    op.create_table(
        "dones",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("note", sa.String(length=4096), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["todoist.tasks.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="todoist",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dones", schema="todoist")
    op.drop_index(op.f("ix_todoist_tasks_title"), table_name="tasks", schema="todoist")
    op.drop_index(op.f("ix_todoist_tasks_status_type"), table_name="tasks", schema="todoist")
    op.drop_table("tasks", schema="todoist")
    # ### end Alembic commands ###
